@startuml

entity A0
entity B0
A0 }o--|| B0

entity A1
entity B1
A1}|--{ B1

entity A2
entity B2
A2"lcomment"}o--o{ B2

entity A3
entity B3
A3 |o--o|"rcomment"B3

entity A4
entity B4
A4||-||                B4

    entity A5
    entity B5
    A5  "lcomment"     ||--||  "rcomment"  B5

package Package1{
    entity A6
    entity B6
    A6 |o-------|{ B6

    entity A7
    entity B7
    A7 }o-------down----------{ B7
}

@enduml