@startuml Pack

entity Z1

!include "sample1.puml"

package Package2
<
    !include "sample3.puml"
    entity A6
    entity A7
    entity A8
    entity A9
    entity B6

    A6 |o--|{ B6
    A6 }o--|{ B6
    A2"lcomment"}o--o{ B2
>

entity Z2
entity Z3

Z2 ||--|| Z3

@enduml